In [76]:
#import variables and read cvs
import pandas as pd
import numpy as np
file = "listings_mexico.csv"
df = pd.read_csv(file, encoding="ISO-8859-1")
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       ...
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object', length=106)

In [77]:
#reduce table for usefull columns
table_df = df.loc[:, ["id", "name", "host_id", "host_name", "neighbourhood_cleansed", "neighbourhood","zipcode", "latitude", "longitude","room_type", "price", "minimum_nights", "number_of_reviews", "last_review", "reviews_per_month", "calculated_host_listings_count", "availability_365", "bed_type", "amenities", "review_scores_rating"]]
table_df.head()

,id,name,host_id,host_name,neighbourhood_cleansed,neighbourhood,zipcode,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,bed_type,amenities,review_scores_rating
0,14714,Private room c/ bathroom . Colonia Juarez.,57785,Diego,CuauhtÃ©moc,JuÃ¡rez,6600,$19.43,$-99.16,Private room,476,2,0,NaN,$nan,1,364,Real Bed,"{Wifi,Kitchen,""Free parking on premises"",""Paid...",$nan
1,22787,"Sunny suite w/ queen size bed, inside boutique...",87973,Diego,CuauhtÃ©moc,San Rafael,6470,$19.44,$-99.16,Private room,1957,1,10,11/05/2018,$0.58,8,0,Real Bed,"{Wifi,""Paid parking off premises"",Breakfast,Wa...",$87.00
2,33681,Couple of Rooms,145672,Edubiel,Tlalpan,NaN,14220,$19.27,$-99.22,Private room,1729,1,0,NaN,$nan,1,365,Real Bed,"{""Free parking on premises"",""Smoking allowed"",...",$nan
3,35797,Villa Dante,153786,Dici,Cuajimalpa de Morelos,NaN,NaN,$19.38,$-99.27,Entire home/apt,3800,1,0,NaN,$nan,2,364,Futon,"{Wifi,Kitchen,""Free parking on premises"",""Indo...",$nan
4,44616,CONDESA HAUS BOUTIQUE B&B,196253,Condesa Haus Bed & BReakfast CDMX,CuauhtÃ©moc,Condesa,6140,$19.41,$-99.18,Private room,1906,1,39,02/05/2019,$0.43,10,330,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Free parking on ...",$89.00

In [78]:
#Check data types
table_df.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_cleansed             object
neighbourhood                      object
zipcode                            object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
bed_type                           object
amenities                          object
review_scores_rating              float64
dtype: object

In [79]:
#Filter database to keep number of reviews higher than 1
#Clean odd characters
table_reviews = table_df.loc[table_df["number_of_reviews"]>=0, ["id", "name", "host_id", "host_name", "neighbourhood_cleansed", "neighbourhood", "zipcode", "latitude", "longitude","room_type", "price", "minimum_nights", "number_of_reviews", "last_review", "reviews_per_month", "calculated_host_listings_count", "availability_365", "bed_type", "amenities", "review_scores_rating"]]
table_reviews['neighbourhood_cleansed'] = table_reviews['neighbourhood_cleansed'].str.replace('Ã©', 'e')
table_reviews['neighbourhood_cleansed'] = table_reviews['neighbourhood_cleansed'].str.replace('Ã¡', 'a')
table_reviews['neighbourhood_cleansed'] = table_reviews['neighbourhood_cleansed'].str.replace('Ã', 'A')
table_reviews['neighbourhood_cleansed'] = table_reviews['neighbourhood_cleansed'].str.replace('Ã³', 'o')

table_reviews['neighbourhood'] = table_reviews['neighbourhood'].str.replace('Ã©', 'e')
table_reviews['neighbourhood'] = table_reviews['neighbourhood'].str.replace('Ã¡', 'a')
table_reviews['neighbourhood'] = table_reviews['neighbourhood'].str.replace('Ã', 'A')
table_reviews['neighbourhood'] = table_reviews['neighbourhood'].str.replace('Ã³', 'o')

table_reviews.head()

,id,name,host_id,host_name,neighbourhood_cleansed,neighbourhood,zipcode,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,bed_type,amenities,review_scores_rating
0,14714,Private room c/ bathroom . Colonia Juarez.,57785,Diego,Cuauhtemoc,Juarez,6600,$19.43,$-99.16,Private room,476,2,0,NaN,$nan,1,364,Real Bed,"{Wifi,Kitchen,""Free parking on premises"",""Paid...",$nan
1,22787,"Sunny suite w/ queen size bed, inside boutique...",87973,Diego,Cuauhtemoc,San Rafael,6470,$19.44,$-99.16,Private room,1957,1,10,11/05/2018,$0.58,8,0,Real Bed,"{Wifi,""Paid parking off premises"",Breakfast,Wa...",$87.00
2,33681,Couple of Rooms,145672,Edubiel,Tlalpan,NaN,14220,$19.27,$-99.22,Private room,1729,1,0,NaN,$nan,1,365,Real Bed,"{""Free parking on premises"",""Smoking allowed"",...",$nan
3,35797,Villa Dante,153786,Dici,Cuajimalpa de Morelos,NaN,NaN,$19.38,$-99.27,Entire home/apt,3800,1,0,NaN,$nan,2,364,Futon,"{Wifi,Kitchen,""Free parking on premises"",""Indo...",$nan
4,44616,CONDESA HAUS BOUTIQUE B&B,196253,Condesa Haus Bed & BReakfast CDMX,Cuauhtemoc,Condesa,6140,$19.41,$-99.18,Private room,1906,1,39,02/05/2019,$0.43,10,330,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Free parking on ...",$89.00

In [80]:
table_reviews.count()

id                                18348
name                              18336
host_id                           18348
host_name                         18344
neighbourhood_cleansed            18348
neighbourhood                     14489
zipcode                           17268
latitude                          18348
longitude                         18348
room_type                         18348
price                             18348
minimum_nights                    18348
number_of_reviews                 18348
last_review                       13821
reviews_per_month                 13821
calculated_host_listings_count    18348
availability_365                  18348
bed_type                          18348
amenities                         18348
review_scores_rating              13592
dtype: int64

In [81]:
no_null_table_reviews = table_reviews.dropna(how='any')

In [82]:
no_null_table_reviews.count()

id                                10696
name                              10696
host_id                           10696
host_name                         10696
neighbourhood_cleansed            10696
neighbourhood                     10696
zipcode                           10696
latitude                          10696
longitude                         10696
room_type                         10696
price                             10696
minimum_nights                    10696
number_of_reviews                 10696
last_review                       10696
reviews_per_month                 10696
calculated_host_listings_count    10696
availability_365                  10696
bed_type                          10696
amenities                         10696
review_scores_rating              10696
dtype: int64

In [83]:
no_null_table_reviews.to_csv("data_base_clean.csv", index=False)