In [10]:
#import variables and read cvs
import pandas as pd
import numpy as np
file = "listings_mexico.csv"
df = pd.read_csv(file, encoding="ISO-8859-1")
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       ...
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object', length=106)

In [16]:
#reduce table for usefull columns
table_df = df.loc[:, ["id", "name", "host_id", "host_name", "neighbourhood_cleansed", "neighbourhood", "latitude", "longitude","room_type", "price", "minimum_nights", "number_of_reviews", "last_review", "reviews_per_month", "calculated_host_listings_count", "availability_365"]]
table_df.head()

,id,name,host_id,host_name,neighbourhood_cleansed,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,14714,Private room c/ bathroom . Colonia Juarez.,57785,Diego,CuauhtÃ©moc,JuÃ¡rez,19.43035,-99.15511,Private room,476,2,0,NaN,NaN,1,364
1,22787,"Sunny suite w/ queen size bed, inside boutique...",87973,Diego,CuauhtÃ©moc,San Rafael,19.44076,-99.16324,Private room,1957,1,10,11/05/2018,0.58,8,0
2,33681,Couple of Rooms,145672,Edubiel,Tlalpan,NaN,19.27215,-99.21848,Private room,1729,1,0,NaN,NaN,1,365
3,35797,Villa Dante,153786,Dici,Cuajimalpa de Morelos,NaN,19.38399,-99.27335,Entire home/apt,3800,1,0,NaN,NaN,2,364
4,44616,CONDESA HAUS BOUTIQUE B&B,196253,Condesa Haus Bed & BReakfast CDMX,CuauhtÃ©moc,Condesa,19.41006,-99.17645,Private room,1906,1,39,02/05/2019,0.43,10,330

In [17]:
#Check data types
table_df.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_cleansed             object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [33]:
#Review odd characters
listado = table_df["neighbourhood_cleansed"].unique()
listado1 = listado.tolist()
listado1

['CuauhtÃ©moc',
 'Tlalpan',
 'Cuajimalpa de Morelos',
 'CoyoacÃ¡n',
 'Miguel Hidalgo',
 'Benito JuÃ¡rez',
 'Azcapotzalco',
 'Iztacalco',
 'Venustiano Carranza',
 'Ã\x81lvaro ObregÃ³n',
 'Iztapalapa',
 'Gustavo A. Madero',
 'Xochimilco',
 'La Magdalena Contreras',
 'TlÃ¡huac',
 'Milpa Alta']

In [34]:
number_of_b= len(listado1)
number_of_b

16

In [37]:
#Filter database to keep number of reviews higher than 1
#Clean odd characters
table_reviews = table_df.loc[table_df["number_of_reviews"]>0, ["id", "name", "host_id", "host_name", "neighbourhood_cleansed", "neighbourhood", "latitude", "longitude","room_type", "price", "minimum_nights", "number_of_reviews", "last_review", "reviews_per_month", "calculated_host_listings_count", "availability_365"]]
table_reviews['neighbourhood_cleansed'] = table_reviews['neighbourhood_cleansed'].str.replace('Ã©', 'e')
table_reviews['neighbourhood_cleansed'] = table_reviews['neighbourhood_cleansed'].str.replace('Ã¡', 'a')
table_reviews['neighbourhood_cleansed'] = table_reviews['neighbourhood_cleansed'].str.replace('Ã', 'A')
table_reviews['neighbourhood_cleansed'] = table_reviews['neighbourhood_cleansed'].str.replace('Ã³', 'o')

table_reviews['neighbourhood'] = table_reviews['neighbourhood'].str.replace('Ã©', 'e')
table_reviews['neighbourhood'] = table_reviews['neighbourhood'].str.replace('Ã¡', 'a')
table_reviews['neighbourhood'] = table_reviews['neighbourhood'].str.replace('Ã', 'A')
table_reviews['neighbourhood'] = table_reviews['neighbourhood'].str.replace('Ã³', 'o')
table_reviews.head()

,id,name,host_id,host_name,neighbourhood_cleansed,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,22787,"Sunny suite w/ queen size bed, inside boutique...",87973,Diego,Cuauhtemoc,San Rafael,19.44076,-99.16324,Private room,1957,1,10,11/05/2018,0.58,8,0
4,44616,CONDESA HAUS BOUTIQUE B&B,196253,Condesa Haus Bed & BReakfast CDMX,Cuauhtemoc,Condesa,19.41006,-99.17645,Private room,1906,1,39,02/05/2019,0.43,10,330
5,58955,Entire beautiful duplex in la Roma,282620,Nat,Cuauhtemoc,Roma Norte,19.42292,-99.15775,Entire home/apt,1620,3,37,01/01/2019,0.41,1,173
6,61792,Spacious Clean Quiet room (own bath) in la Con...,299558,Roberto,Cuauhtemoc,Condesa,19.41259,-99.17959,Private room,953,2,51,05/04/2019,2.69,3,180
7,67703,"2 bedroom apt. deco bldg, Condesa",334451,Nicholas,Cuauhtemoc,Hipodromo,19.41375,-99.17028,Entire home/apt,1810,2,39,24/02/2019,0.43,3,340